apiVersion: v2
description: Custom Helm chart for OpenCost
name: opencost
version: 0.1.0
dependencies:
  - name: opencost
    version: 1.43.1
    repository: https://opencost.github.io/opencost-helm-chart
