opencost:
  customPricing:
    enabled: true
    costModel:
      description: Modified pricing configuration.
      CPU: 1.26
      RAM: 0.60
      GPU: 0.96
      storage: 0.25

  prometheus:
    internal:
      enabled: false
    serverEndpoint: "http://prometheus-server.monitoring.svc.cluster.local:80"


loglevel: debug



