opencost:
  loglevel: debug

  opencost:
    clusterID: "k3s-cluster"
    exporter:
      replicas: 3
    customPricing:
      enabled: true
      costModel:
        description: Modified pricing configuration.
        CPU: 1.26
        RAM: 0.60
        GPU: 0.96
        storage: 0.25
    prometheus:
      external:
        enabled: false
      internal:
        enabled: true
        serviceName: prometheus-server
        namespaceName: monitoring
        port: 80
